### ISSUE TITLE
when building via a click in Github Actions, don't create tag named main as side effect

### ISSUE THREAD

**Issue by jeremybmerrill** [jeremybmerrill/meaningfully#35]
when there's a tag named main, git really acts up :(

the problem is:

```
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
```

because `github.ref_name` when run against main is, predictably, main.
